# Utilise l’image Ubuntu la plus récente comme base
FROM ubuntu:latest

# Met à jour APT et met à jour les paquets installés
RUN apt-get update && apt-get upgrade -y

# Commande par défaut quand le conteneur démarre
CMD ["echo", "Hello, World!"]
